name: Build and deploy development

on:
  push:
    branches:
      - develop
      - feature/MU-23-setup-cicd-web-admin
    paths:
      - src
      - .github/workflows/build-and-deploy-dev.yml

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "./src/build/*"
          target: "/var/www/admin-mentorus.hieucckha.me/html"
          rm: true

      - name: Remove all old file
        uses: appleboy/ssh-action@v1.0.0
        with:
          script_stop: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Move all file to root folder
            mv /var/www/admin-mentorus.hieucckha.me/html/src/build/* /var/www/admin-mentorus.hieucckha.me/html
            rm -rf /var/www/admin-mentorus.hieucckha.me/html/src
