name: Build and deploy MentorUS web-admin (Development)

on:
  push:
    branches:
      - develop
      - feature/MU-23-setup-cicd-web-admin
    paths:
      - src
      - .github/workflows/build-and-deploy-dev.yml

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Remove all old file
        uses: appleboy/ssh-action@v1.0.0
        with:
          script_stop: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: ${{ secrets.PAT_GITHUB_TOKEN }}, ${{ github.actor }}, ${{ env.CONTAINER_NAME }},
          script: |
            # Remove all old file build
            rm -rf /var/www/admin-mentorus.hieucckha.me/html/*

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "src/build/*"
          target: "/var/www/admin-mentorus.hieucckha.me/html"
