name: Component Testings

on:
  push:
    branches:
      - "feature/**"
      - "develop"
    paths:
      - "src/**"
      - .github/workflows/component-test.yml
      
  workflow_dispatch:

jobs:
  component-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Decode Cypress env json
        uses: timheuer/base64-to-file@v1
        id: cypress_env_json
        with:
          fileName: "cypress.env.json"
          fileDir: "./src/"
          encodedString: ${{ secrets.CYPRESS_ENV_JSON }}

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: src
          component: true
        env:
          CYPRESS_XRAY_UPLOAD_RESULTS: false
    
      # Upload screenshots and videos as artifacts if the tests fail
      - name: Upload failed screenshots and videos as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`