name: End-to-end Smoke Testings

on:
  schedule:
    - cron: "30 5 * * 1,5" # Run on 5:30 at Mon,Fri

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest"]
        containers: [1, 2, 3]

    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} - Run test on Chrome
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PAT_GITHUB_TOKEN: op://mentorus/github-pat-publish-package/token

      - name: Inject secret with 1Password
        run: |
          export OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          op inject -i ./src/cypress.env.json.tpl -o ./src/cypress.env.json

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     install-command: yarn --frozen-lockfile --network-timeout 100000
      #     working-directory: src
      #     start: yarn startTest
      #     wait-on: "http://localhost:3000"
      #     wait-on-timeout: 180
      #     browser: chrome
      #     spec: cypress/e2e/smoke_test/*.cy.js
      #     headed: true
      #   env:
      #     CYPRESS_PLUGIN_DEBUG: true
      #     CYPRESS_JIRA_TEST_EXECUTION_ISSUE_SUMMARY: "[Web Admin - Chrome] Smoke test execution"

      - name: Cypress run split
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn --frozen-lockfile --network-timeout 100000
          working-directory: src
          start: yarn startTest
          wait-on: "http://localhost:3000"
          wait-on-timeout: 180
          browser: chrome
          headed: true
          spec: |
            **/smoke_test/*LoginPage.cy.js
            **/smoke_test/*StatisticPage.cy.js
            **/smoke_test/*SystemConfig.cy.js
            **/smoke_test/*MyProfile.cy.js
        env:
          DEBUG: 'cypress-split,find-cypress-specs'
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          CYPRESS_PLUGIN_DEBUG: true
          CYPRESS_JIRA_TEST_EXECUTION_ISSUE_SUMMARY: "[Web Admin - Chrome] Smoke test execution"
          
      # Upload screenshots and videos as artifacts if the tests fail
      - name: Upload failed screenshots as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Upload failed videos as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

