name: End-to-end Testings Chrome

on:
  push:
    branches:
      - feature/**
    paths:
      - src
      - .github/workflows/e2e-test-chrome.yml
      
  workflow_dispatch:

jobs:
  e2e-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: src
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome

      # Upload screenshots and videos as artifacts if the tests fail
      - name: Upload failed screenshots and videos as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`