name: End-to-end Testings

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - "src/**"
      - .github/workflows/e2e-test.yml
      
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        browser: [chrome, firefox, edge]
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} - Run test on ${{ matrix.browser }} 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn --frozen-lockfile --network-timeout 100000
          working-directory: src
          start: yarn dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          browser: ${{ matrix.browser }}

      # Upload screenshots and videos as artifacts if the tests fail
      - name: Upload failed screenshots as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      
      - name: Upload failed videos as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`